# Sex-Stratified Model Fit Comparison
#
# Compares model fit metrics across combined-sample, female-only, and male-only
# analyses: testRMSE (lower=better), testLPS (higher=better), testARI,
# SALSO Binder/VI ARI, and 5-fold CV RMSE.
#
# Inputs (generated by 06/06b/06c + 08/08b/08c):
#   output/baselines/frftotalComparison.csv              (combined)
#   output/baselines-female/frftotalComparison.csv       (female)
#   output/baselines-male/frftotalComparison.csv         (male)
#   output/baselines/combined5foldCV.csv
#   output/baselines-female/combined5foldCV.csv
#   output/baselines-male/combined5foldCV.csv
#
# Outputs to output/sexStratifiedMfit/:
#   mfit_comparison.csv     master table (sample x model x metric)
#   mfit_deltas.csv         deltas vs combined (female-combined, male-combined)
#   fig_rmse.png            testRMSE by model, grouped by sample
#   fig_lps.png             testLPS by model, grouped by sample
#   fig_ari.png             testARI + SALSO Binder/VI ARI by model, grouped
#   fig_cv_fold.png         per-fold CV RMSE across samples
#
# CAVEAT: Metrics are computed on different test sets (all vs female vs male
# subjects). This is a descriptive sensitivity check, NOT a paired statistical
# comparison. Different sample sizes and different FRF subject subsets mean
# direct numerical comparison is not strictly valid.
#
# Run on HPC (from analyses/):
#   module load R/4.4.0-openblas-rocky8
#   Rscript compareSexStratified-Mfit.R

library(tidyverse)
library(gt)
library(ggsci)

out_dir <- "output/sexStratifiedMfit"
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

read_baseline <- function(path, sample_name) {
  if (!file.exists(path)) {
    message("  MISSING: ", path)
    return(NULL)
  }
  df <- read_csv(path, show_col_types = FALSE)
  df$sample <- sample_name
  df
}

read_cv <- function(path, sample_name) {
  if (!file.exists(path)) {
    message("  MISSING: ", path)
    return(NULL)
  }
  df <- read_csv(path, show_col_types = FALSE)
  df$sample <- sample_name
  df
}

# --- read baseline comparisons ---
base_combined <- read_baseline("output/baselines/frftotalComparison.csv", "combined")
base_female   <- read_baseline("output/baselines-female/frftotalComparison.csv", "female")
base_male     <- read_baseline("output/baselines-male/frftotalComparison.csv", "male")

# --- read CV fold RMSE ---
cv_combined <- read_cv("output/baselines/combined5foldCV.csv", "combined")
cv_female   <- read_cv("output/baselines-female/combined5foldCV.csv", "female")
cv_male     <- read_cv("output/baselines-male/combined5foldCV.csv", "male")

all_base <- bind_rows(base_combined, base_female, base_male)
all_cv   <- bind_rows(cv_combined, cv_female, cv_male)

if (nrow(all_base) == 0) {
  message("\nNo baseline files found. Run 06/06b/06c first.")
  quit(status = 0)
}

# --- reshape to long for metrics ---
metric_cols <- c(
  "testRMSE", "testLPS", "testARI",
  "testARISalsoBinder", "testARISalsoVI",
  "testARImodalSalsoBinder", "testARImodalSalsoVI",
  "nclusters"
)

base_long <- all_base %>%
  select(sample, model, any_of(metric_cols)) %>%
  pivot_longer(cols = any_of(metric_cols), names_to = "metric", values_to = "value") %>%
  filter(!is.na(value))

# direction: -1 means lower is better (RMSE), +1 means higher is better (everything else)
metric_dir <- tibble(
  metric = metric_cols,
  higher_better = c(FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, NA)
)

base_long <- base_long %>%
  left_join(metric_dir, by = "metric")

# --- wide table for output ---
base_wide <- all_base %>%
  select(sample, model, any_of(metric_cols)) %>%
  arrange(sample, model)

write_csv(base_wide, file.path(out_dir, "mfit_comparison.csv"))

# --- deltas vs combined ---
if (!is.null(base_combined)) {
  models <- unique(base_combined$model)
  delta_rows <- list()
  for (m in models) {
    row_c <- base_combined %>% filter(model == m)
    row_f <- base_female %>% filter(model == m)
    row_m <- base_male %>% filter(model == m)

    for (met in metric_cols) {
      vc <- row_c[[met]]
      vf <- row_f[[met]]
      vm <- row_m[[met]]
      hb <- metric_dir %>% filter(metric == met) %>% pull(higher_better)

      d_f <- if (is.null(vf) || is.na(vf) || is.null(vc) || is.na(vc)) NA_real_ else as.numeric(vf) - as.numeric(vc)
      d_m <- if (is.null(vm) || is.na(vm) || is.null(vc) || is.na(vc)) NA_real_ else as.numeric(vm) - as.numeric(vc)

      better_f <- if (is.na(d_f)) NA else if (isTRUE(hb)) d_f > 0 else d_f < 0
      better_m <- if (is.na(d_m)) NA else if (isTRUE(hb)) d_m > 0 else d_m < 0

      delta_rows <- append(delta_rows, list(tibble(
        model = m, metric = met,
        female_delta = d_f, female_better = better_f,
        male_delta   = d_m, male_better   = better_m
      )))
    }
  }
  deltas <- bind_rows(delta_rows)
  write_csv(deltas, file.path(out_dir, "mfit_deltas.csv"))
} else {
  deltas <- tibble()
  message("Combined baseline missing; no deltas computed.")
}

# --- print gt verdict table ---
cat("\n=== SEX-STRATIFIED MODEL FIT COMPARISON ===\n")
cat("Caveat: Metrics computed on different test sets (all vs female vs male).\n")
cat("This is descriptive; not a paired statistical test.\n\n")

# Combine base_wide with delta markers for printing
if (nrow(deltas) > 0) {
  for (m in unique(base_wide$model)) {
    cat(sprintf("\n--- Model: %s ---\n", m))
    row_c <- base_wide %>% filter(sample == "combined", model == m)
    row_f <- base_wide %>% filter(sample == "female", model == m)
    row_m <- base_wide %>% filter(sample == "male", model == m)
    row_d <- deltas %>% filter(model == m)

    for (met in metric_cols) {
      vc <- row_c[[met]]; vf <- row_f[[met]]; vm <- row_m[[met]]
      df <- row_d %>% filter(metric == met) %>% pull(female_delta)
      dm <- row_d %>% filter(metric == met) %>% pull(male_delta)
      bf <- row_d %>% filter(metric == met) %>% pull(female_better)
      bm <- row_d %>% filter(metric == met) %>% pull(male_better)

      parts <- c()
      if (!is.null(vc) && !is.na(vc)) parts <- c(parts, sprintf("combined=%.4f", vc))
      if (!is.null(vf) && !is.na(vf)) {
        mark <- if (!is.na(bf)) if (bf) "▲" else "▼" else " "
        parts <- c(parts, sprintf("female=%.4f%s", vf, mark))
      }
      if (!is.null(vm) && !is.na(vm)) {
        mark <- if (!is.na(bm)) if (bm) "▲" else "▼" else " "
        parts <- c(parts, sprintf("male=%.4f%s", vm, mark))
      }
      cat(sprintf("  %s: %s\n", met, paste(parts, collapse = " | ")))
    }
  }
}

# gt table
if (nrow(deltas) > 0) {
  gt_tbl <- base_wide %>%
    pivot_longer(cols = any_of(metric_cols), names_to = "metric", values_to = "value") %>%
    left_join(deltas %>% pivot_longer(cols = c(female_delta, male_delta), names_to = "delta_type", values_to = "delta"), by = c("model", "metric")) %>%
    left_join(deltas %>% pivot_longer(cols = c(female_better, male_better), names_to = "better_type", values_to = "better"), by = c("model", "metric")) %>%
    pivot_wider(names_from = sample, values_from = value) %>%
    mutate(
      marker = case_when(
        is.na(better) ~ "",
        better == TRUE ~ "▲",
        better == FALSE ~ "▼",
        TRUE ~ ""
      )
    ) %>%
    select(model, metric, combined, female, male, delta, marker) %>%
    gt() %>%
    tab_header(title = "Model Fit: Combined vs Female vs Male") %>%
    fmt_number(decimals = 4) %>%
    tab_footnote(footnote = "▲ = better than combined; ▼ = worse; blank = missing or combined ref")

  print(gt_tbl)
}

# --- FIGURES ---

theme_mfit <- theme_bw(base_size = 12) +
  theme(
    strip.background = element_rect(fill = "grey92", colour = NA),
    strip.text = element_text(face = "bold", size = 11),
    legend.position = "bottom",
    legend.key.size = unit(0.35, "cm"),
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", size = 13),
    plot.subtitle = element_text(colour = "grey40", size = 10),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10)
  )

sample_colors <- c("combined" = "#999999", "female" = "#E64B35", "male" = "#4DBBD5")

# 1. RMSE
if ("testRMSE" %in% unique(base_long$metric)) {
  p_rmse <- base_long %>%
    filter(metric == "testRMSE") %>%
    ggplot(aes(x = model, y = value, color = sample, group = sample)) +
    geom_point(size = 3.5, position = position_dodge(width = 0.5)) +
    geom_line(position = position_dodge(width = 0.5), linewidth = 0.8, alpha = 0.6) +
    scale_color_manual(values = sample_colors) +
    labs(x = "Model", y = "Test RMSE (lower = better)",
         title = "Test RMSE: Combined vs Female vs Male",
         subtitle = "Posterior predictive RMSE on FRF test set") +
    theme_mfit
  ggsave(file.path(out_dir, "fig_rmse.png"), p_rmse, width = 10, height = 6, dpi = 300)
  message("Saved fig_rmse.png")
}

# 2. LPS
if ("testLPS" %in% unique(base_long$metric)) {
  p_lps <- base_long %>%
    filter(metric == "testLPS") %>%
    ggplot(aes(x = model, y = value, color = sample, group = sample)) +
    geom_point(size = 3.5, position = position_dodge(width = 0.5)) +
    geom_line(position = position_dodge(width = 0.5), linewidth = 0.8, alpha = 0.6) +
    scale_color_manual(values = sample_colors) +
    labs(x = "Model", y = "Test LPS (higher = better)",
         title = "Test Log Predictive Score: Combined vs Female vs Male",
         subtitle = "LPS = proper scoring rule (Rev 1 C4)") +
    theme_mfit
  ggsave(file.path(out_dir, "fig_lps.png"), p_lps, width = 10, height = 6, dpi = 300)
  message("Saved fig_lps.png")
}

# 3. ARI family (testARI + SALSO Binder/VI)
ari_metrics <- c("testARI", "testARISalsoBinder", "testARISalsoVI",
                 "testARImodalSalsoBinder", "testARImodalSalsoVI")
if (any(ari_metrics %in% unique(base_long$metric))) {
  ari_long <- base_long %>% filter(metric %in% ari_metrics)
  ari_long$metric <- factor(ari_long$metric, levels = ari_metrics)

  p_ari <- ggplot(ari_long, aes(x = model, y = value, color = sample, group = sample)) +
    geom_point(size = 3.5, position = position_dodge(width = 0.5)) +
    geom_line(position = position_dodge(width = 0.5), linewidth = 0.8, alpha = 0.6) +
    facet_wrap(~metric, scales = "free_y", ncol = 3) +
    scale_color_manual(values = sample_colors) +
    labs(x = "Model", y = "ARI (higher = better)",
         title = "Clustering Agreement: Combined vs Female vs Male",
         subtitle = "vs FRF community labels (test set)") +
    theme_mfit +
    theme(legend.position = "bottom")
  ggsave(file.path(out_dir, "fig_ari.png"), p_ari, width = 14, height = 5, dpi = 300)
  message("Saved fig_ari.png")
}

# 4. CV fold RMSE
if (nrow(all_cv) > 0) {
  p_cv <- all_cv %>%
    ggplot(aes(x = factor(fold), y = rmse, fill = sample)) +
    geom_violin(alpha = 0.55, linewidth = 0.4, position = position_dodge(width = 0.8), draw_quantiles = c(0.25, 0.5, 0.75)) +
    stat_summary(fun = median, geom = "point", size = 2.5, color = "black", position = position_dodge(width = 0.8)) +
    geom_hline(data = all_cv %>% group_by(sample) %>% summarise(m = mean(rmse, na.rm = TRUE)),
               aes(yintercept = m, color = sample), linetype = "dashed", linewidth = 0.8) +
    scale_fill_manual(values = sample_colors) +
    scale_color_manual(values = sample_colors) +
    labs(x = "Fold", y = "OOS RMSE",
         title = "5-Fold CV RMSE: Combined vs Female vs Male",
         subtitle = "PPMx-common only; points = fold median; dashed = sample mean") +
    theme_mfit
  ggsave(file.path(out_dir, "fig_cv_fold.png"), p_cv, width = 10, height = 6, dpi = 300)
  message("Saved fig_cv_fold.png")
}

message("\nDone. Outputs in ", out_dir, "/")